### ISSUE TITLE
Error Empty blktrace run found, exiting

### ISSUE THREAD

**Issue by kakito** [trofi/seekwatcher#2]
Hi all,
I was used command: blktrace -d /dev/sda1 -o resuftsda1 -w 30

Then, I used comand: seekwatcher -t resuftsda1.blktrace.0 -o image.png

I I get the message: 
run_blkparse on resuftsda1.blktrace.0
using tracefile resuftsda1
Empty blktrace run found, exiting 

Please help me!
Thanks!

**Comment by trofi** [comment]
Closing as obsolete.
