### ISSUE TITLE
To compare multiple traces , seekwatcher scripts has a small bug 

### ISSUE THREAD

**Issue by cityvigil** [trofi/seekwatcher#3]
[root@client1 cmd]#   ./seekwatcher -t ddtest.trace -t iozone.trace -l ddd -l iozzz -o dd_vs_iozone.png
using tracefile ./ddtest.trace
using tracefile ./iozone.trace
Traceback (most recent call last):
  File "./seekwatcher", line 1020, in <module>
    if data != None:

---fix it 
changed it.
   1020     #if data != None:   <<<<<<
   1021     if data is  None:
   1022         data = runs[i].data
   1023     else:
   1024         data = numpy.append(data, runs[i].data, axis=0

**Comment by trofi** [comment]
Thank you for the report! I changed `== None` to `is None` in a few places as https://github.com/trofi/seekwatcher/commit/e592297cef8481ce16f719235c37c84a3270d2eb. Woes it work for you?

I'll check if `seekwatcher` still works on newer python versions and tag a new release.

**Comment by trofi** [comment]
I also added a reference to `iowatcher`, a successor of `seekwatcher` which you might be interested in: https://github.com/trofi/seekwatcher/commit/3d674d1e06990d54b66662cf9bdf7b7a06c35629

**Comment by trofi** [comment]
Pushed release 0.14 with a few more compatibility fixes for modern environment: https://github.com/trofi/seekwatcher/releases/tag/v0.14
